### ISSUE TITLE
Does L1loss alignment distort the content of edge frames?

### ISSUE THREAD

**Issue by NTGN** [YapengTian/TDAN_VSR#6]
Question about authors using deformable convolution to align different frames：
1.Using Θ to align the picture is suitable in a network similar to 'STN', but the deformable convolution contains 'offset' and 'convolution'. The existence of convolution may make the output not only aligned, but also Loss (introduction) of information that is not in the input, which violates the original intention of alignment
2.With the ‘L1’loss constraint, the content of all frames is moved closer to the reference frame, which may violate the idea of alignment. The content of the aligned edge frame is only the copy of the reference frame.
Can you explain your thoughts to these two doubts? Looking forward to your reply

**Comment by YapengTian** [comment]
1. The deformable alignment is not like optical flow-based methods or STN based methods, it can actually predict missing content due to occlusions by adaptively aggregating contextual pixels. It is not simply predicted pixel movements as previous methods.

2. Note that the aligned frames are predicted with features of the corresponding supporting frames, so it will not just predict the exact same image as the ref frame but will capture subpixel motions for easing the downstream SR task. But, the loss does affect performance. If we use a larger weight for this loss term, the performance will actually drop.

**Comment by NTGN** [comment]
@doubts，Thank you for your reply, it solved my doubts.

**Comment by NTGN** [comment]
@YapengTian ，Thank you for your reply, it solved my doubts.
